INSERT INTO `seller`.`country` (`name`) VALUES ('Abchazja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Afganistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Albania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Algieria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Andora');
INSERT INTO `seller`.`country` (`name`) VALUES ('Angola');
INSERT INTO `seller`.`country` (`name`) VALUES ('Antigua I Barbuda');
INSERT INTO `seller`.`country` (`name`) VALUES ('Arabia Saudyjska');
INSERT INTO `seller`.`country` (`name`) VALUES ('Argentyna');
INSERT INTO `seller`.`country` (`name`) VALUES ('Armenia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Australia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Austria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Azerbejdżan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bahamy');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bahrajn');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bangladesz');
INSERT INTO `seller`.`country` (`name`) VALUES ('Barbados');
INSERT INTO `seller`.`country` (`name`) VALUES ('Belgia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Belize');
INSERT INTO `seller`.`country` (`name`) VALUES ('Benin');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bhutan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Białoruś');
INSERT INTO `seller`.`country` (`name`) VALUES ('Birma');
INSERT INTO `seller`.`country` (`name`) VALUES ('Boliwia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bośnia I Hercegowina');
INSERT INTO `seller`.`country` (`name`) VALUES ('Botswana');
INSERT INTO `seller`.`country` (`name`) VALUES ('Brazylia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Brunei');
INSERT INTO `seller`.`country` (`name`) VALUES ('Bułgaria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Burkina Faso');
INSERT INTO `seller`.`country` (`name`) VALUES ('Burundi');
INSERT INTO `seller`.`country` (`name`) VALUES ('Chile');
INSERT INTO `seller`.`country` (`name`) VALUES ('Chińska Republika Ludowa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Chorwacja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Cypr');
INSERT INTO `seller`.`country` (`name`) VALUES ('Cypr Północny');
INSERT INTO `seller`.`country` (`name`) VALUES ('Czad');
INSERT INTO `seller`.`country` (`name`) VALUES ('Czarnogóra');
INSERT INTO `seller`.`country` (`name`) VALUES ('Dania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Demokratyczna Republika Konga');
INSERT INTO `seller`.`country` (`name`) VALUES ('Dominika');
INSERT INTO `seller`.`country` (`name`) VALUES ('Dominikana');
INSERT INTO `seller`.`country` (`name`) VALUES ('Dżibuti');
INSERT INTO `seller`.`country` (`name`) VALUES ('Egipt');
INSERT INTO `seller`.`country` (`name`) VALUES ('Ekwador');
INSERT INTO `seller`.`country` (`name`) VALUES ('Erytrea');
INSERT INTO `seller`.`country` (`name`) VALUES ('Estonia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Etiopia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Fidżi');
INSERT INTO `seller`.`country` (`name`) VALUES ('Filipiny');
INSERT INTO `seller`.`country` (`name`) VALUES ('Finlandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Francja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gabon');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gambia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Ghana');
INSERT INTO `seller`.`country` (`name`) VALUES ('Górski Karabach');
INSERT INTO `seller`.`country` (`name`) VALUES ('Grecja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Grenada');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gruzja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gujana');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gwatemala');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gwinea');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gwinea Bissau');
INSERT INTO `seller`.`country` (`name`) VALUES ('Gwinea Równikowa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Haiti');
INSERT INTO `seller`.`country` (`name`) VALUES ('Hiszpania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Holandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Honduras');
INSERT INTO `seller`.`country` (`name`) VALUES ('Indie');
INSERT INTO `seller`.`country` (`name`) VALUES ('Indonezja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Irak');
INSERT INTO `seller`.`country` (`name`) VALUES ('Iran');
INSERT INTO `seller`.`country` (`name`) VALUES ('Irlandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Islandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Izrael');
INSERT INTO `seller`.`country` (`name`) VALUES ('Jamajka');
INSERT INTO `seller`.`country` (`name`) VALUES ('Japonia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Jemen');
INSERT INTO `seller`.`country` (`name`) VALUES ('Jordania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kambodża');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kamerun');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kanada');
INSERT INTO `seller`.`country` (`name`) VALUES ('Katar');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kazachstan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kenia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kirgistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kiribati');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kolumbia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Komory');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kongo');
INSERT INTO `seller`.`country` (`name`) VALUES ('Korea Południowa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Korea Północna');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kosowo');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kostaryka');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kuba');
INSERT INTO `seller`.`country` (`name`) VALUES ('Kuwejt');
INSERT INTO `seller`.`country` (`name`) VALUES ('Laos');
INSERT INTO `seller`.`country` (`name`) VALUES ('Lesotho');
INSERT INTO `seller`.`country` (`name`) VALUES ('Liban');
INSERT INTO `seller`.`country` (`name`) VALUES ('Liberia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Libia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Liechtenstein');
INSERT INTO `seller`.`country` (`name`) VALUES ('Litwa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Luksemburg');
INSERT INTO `seller`.`country` (`name`) VALUES ('Łotwa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Macedonia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Madagaskar');
INSERT INTO `seller`.`country` (`name`) VALUES ('Malawi');
INSERT INTO `seller`.`country` (`name`) VALUES ('Malediwy');
INSERT INTO `seller`.`country` (`name`) VALUES ('Malezja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mali');
INSERT INTO `seller`.`country` (`name`) VALUES ('Malta');
INSERT INTO `seller`.`country` (`name`) VALUES ('Maroko');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mauretania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mauritius');
INSERT INTO `seller`.`country` (`name`) VALUES ('Meksyk');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mikronezja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mołdawia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Monako');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mongolia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Mozambik');
INSERT INTO `seller`.`country` (`name`) VALUES ('Naddniestrze');
INSERT INTO `seller`.`country` (`name`) VALUES ('Namibia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Nauru');
INSERT INTO `seller`.`country` (`name`) VALUES ('Nepal');
INSERT INTO `seller`.`country` (`name`) VALUES ('Niemcy');
INSERT INTO `seller`.`country` (`name`) VALUES ('Niger');
INSERT INTO `seller`.`country` (`name`) VALUES ('Nigeria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Nikaragua');
INSERT INTO `seller`.`country` (`name`) VALUES ('Norwegia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Nowa Zelandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Oman');
INSERT INTO `seller`.`country` (`name`) VALUES ('Osetia Południowa');
INSERT INTO `seller`.`country` (`name`) VALUES ('Pakistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Palau');
INSERT INTO `seller`.`country` (`name`) VALUES ('Palestyna');
INSERT INTO `seller`.`country` (`name`) VALUES ('Panama');
INSERT INTO `seller`.`country` (`name`) VALUES ('Papua Nowa Gwinea');
INSERT INTO `seller`.`country` (`name`) VALUES ('Paragwaj');
INSERT INTO `seller`.`country` (`name`) VALUES ('Peru');
INSERT INTO `seller`.`country` (`name`) VALUES ('Polska');
INSERT INTO `seller`.`country` (`name`) VALUES ('Portugalia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Republika Czeska');
INSERT INTO `seller`.`country` (`name`) VALUES ('Republika Południowej Afryki');
INSERT INTO `seller`.`country` (`name`) VALUES ('Republika Środkowoafrykańska');
INSERT INTO `seller`.`country` (`name`) VALUES ('Republika Zielonego Przylądka');
INSERT INTO `seller`.`country` (`name`) VALUES ('Rosja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Rumunia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Rwanda');
INSERT INTO `seller`.`country` (`name`) VALUES ('Sahara Zachodnia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Saint Kitts I Nevis');
INSERT INTO `seller`.`country` (`name`) VALUES ('Saint Lucia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Saint Vincent I Grenadyny');
INSERT INTO `seller`.`country` (`name`) VALUES ('Salwador');
INSERT INTO `seller`.`country` (`name`) VALUES ('Samoa');
INSERT INTO `seller`.`country` (`name`) VALUES ('San Marino');
INSERT INTO `seller`.`country` (`name`) VALUES ('Senegal');
INSERT INTO `seller`.`country` (`name`) VALUES ('Serbia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Seszele');
INSERT INTO `seller`.`country` (`name`) VALUES ('Sierra Leone');
INSERT INTO `seller`.`country` (`name`) VALUES ('Singapur');
INSERT INTO `seller`.`country` (`name`) VALUES ('Słowacja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Słowenia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Somalia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Somaliland');
INSERT INTO `seller`.`country` (`name`) VALUES ('Sri Lanka');
INSERT INTO `seller`.`country` (`name`) VALUES ('Stany Zjednoczone');
INSERT INTO `seller`.`country` (`name`) VALUES ('Suazi');
INSERT INTO `seller`.`country` (`name`) VALUES ('Sudan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Surinam');
INSERT INTO `seller`.`country` (`name`) VALUES ('Syria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Szwajcaria');
INSERT INTO `seller`.`country` (`name`) VALUES ('Szwecja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tadżykistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tajlandia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tajwan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tanzania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Timor Wschodni');
INSERT INTO `seller`.`country` (`name`) VALUES ('Togo');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tonga');
INSERT INTO `seller`.`country` (`name`) VALUES ('Trynidad I Tobago');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tunezja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Turcja');
INSERT INTO `seller`.`country` (`name`) VALUES ('Turkmenistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Tuvalu');
INSERT INTO `seller`.`country` (`name`) VALUES ('Uganda');
INSERT INTO `seller`.`country` (`name`) VALUES ('Ukraina');
INSERT INTO `seller`.`country` (`name`) VALUES ('Urugwaj');
INSERT INTO `seller`.`country` (`name`) VALUES ('Uzbekistan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Vanuatu');
INSERT INTO `seller`.`country` (`name`) VALUES ('Watykan');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wenezuela');
INSERT INTO `seller`.`country` (`name`) VALUES ('Węgry');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wielka Brytania');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wietnam');
INSERT INTO `seller`.`country` (`name`) VALUES ('Włochy');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wybrzeże Kości Słoniowej');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wyspy Marshalla');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wyspy Salomona');
INSERT INTO `seller`.`country` (`name`) VALUES ('Wyspy Świętego Tomasza I Książęca');
INSERT INTO `seller`.`country` (`name`) VALUES ('Zambia');
INSERT INTO `seller`.`country` (`name`) VALUES ('Zimbabwe');
INSERT INTO `seller`.`country` (`name`) VALUES ('Zjednoczone Emiraty Arabskie');

INSERT INTO seller.address_type (added, modified, deleted, name, is_default) VALUES ('2017-01-29 23:09:47', '2017-01-29 23:09:47', null, 'Zameldowania', true);
INSERT INTO seller.address_type (added, modified, deleted, name, is_default) VALUES ('2017-01-29 23:09:47', '2017-01-29 23:09:47', null, 'Zamieszkania', null);
INSERT INTO seller.address_type (added, modified, deleted, name, is_default) VALUES ('2017-01-29 23:09:47', '2017-01-29 23:09:47', null, 'Korespondencji', null);
INSERT INTO seller.address_type (added, modified, deleted, name, is_default) VALUES ('2017-01-29 23:09:47', '2017-01-29 23:09:47', null, 'Inny', null);

INSERT INTO seller.menu (added, modified, deleted, name, pos, is_default) VALUES ('2017-01-28 13:24:09', '2017-01-28 13:24:09', null, 'MainMenu', null, null);

INSERT INTO seller.menu_item (added, modified, deleted, name, display_name, href, menu_id, PARENT_ID, is_default) VALUES ('2017-01-28 13:24:48', '2017-01-28 13:24:48', null, 'Dashboard', 'Dashboard', null, 1, null, null);
INSERT INTO seller.menu_item (added, modified, deleted, name, display_name, href, menu_id, PARENT_ID, is_default) VALUES ('2017-01-28 13:24:48', '2017-01-28 13:24:48', null, 'Sklep', 'Sklep', null, 1, null, null);
INSERT INTO seller.menu_item (added, modified, deleted, name, display_name, href, menu_id, PARENT_ID, is_default) VALUES ('2017-01-28 13:25:38', '2017-01-28 13:25:38', null, 'Klienci', 'Klienci', null, 1, 2, null);
INSERT INTO seller.menu_item (added, modified, deleted, name, display_name, href, menu_id, PARENT_ID, is_default) VALUES ('2017-01-28 13:25:38', '2017-01-28 13:25:38', null, 'Płatności', 'Płatności', null, 1, 2, null);
INSERT INTO seller.menu_item (added, modified, deleted, name, display_name, href, menu_id, PARENT_ID, is_default) VALUES ('2017-01-28 13:25:38', '2017-01-28 13:25:38', null, 'Oferty', 'Oferty', null, 1, 2, null);