//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressInfoStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressInfoStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="addressUserData" type="{https://webapi.allegro.pl/service.php}AddressUserDataStruct"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressInfoStruct", propOrder = {

})
public class AddressInfoStruct {

    protected int addressType;
    @XmlElement(required = true)
    protected AddressUserDataStruct addressUserData;

    /**
     * Gets the value of the addressType property.
     * 
     */
    public int getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     */
    public void setAddressType(int value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the addressUserData property.
     * 
     * @return
     *     possible object is
     *     {@link AddressUserDataStruct }
     *     
     */
    public AddressUserDataStruct getAddressUserData() {
        return addressUserData;
    }

    /**
     * Sets the value of the addressUserData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressUserDataStruct }
     *     
     */
    public void setAddressUserData(AddressUserDataStruct value) {
        this.addressUserData = value;
    }

}
