//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoriesListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoriesListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="categoriesTree" type="{https://webapi.allegro.pl/service.php}ArrayOfCategorytreetype" minOccurs="0"/&gt;
 *         &lt;element name="categoriesPath" type="{https://webapi.allegro.pl/service.php}ArrayOfCategorypathtype" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoriesListType", propOrder = {

})
public class CategoriesListType {

    protected ArrayOfCategorytreetype categoriesTree;
    protected ArrayOfCategorypathtype categoriesPath;

    /**
     * Gets the value of the categoriesTree property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCategorytreetype }
     *     
     */
    public ArrayOfCategorytreetype getCategoriesTree() {
        return categoriesTree;
    }

    /**
     * Sets the value of the categoriesTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCategorytreetype }
     *     
     */
    public void setCategoriesTree(ArrayOfCategorytreetype value) {
        this.categoriesTree = value;
    }

    /**
     * Gets the value of the categoriesPath property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCategorypathtype }
     *     
     */
    public ArrayOfCategorypathtype getCategoriesPath() {
        return categoriesPath;
    }

    /**
     * Sets the value of the categoriesPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCategorypathtype }
     *     
     */
    public void setCategoriesPath(ArrayOfCategorypathtype value) {
        this.categoriesPath = value;
    }

}
