//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cancelBidValue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cancelledBids" type="{https://webapi.allegro.pl/service.php}ArrayOfInt" minOccurs="0"/&gt;
 *         &lt;element name="notCancelledBids" type="{https://webapi.allegro.pl/service.php}ArrayOfInt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cancelBidValue",
    "cancelledBids",
    "notCancelledBids"
})
@XmlRootElement(name = "doCancelBidItemResponse")
public class DoCancelBidItemResponse {

    protected int cancelBidValue;
    protected ArrayOfInt cancelledBids;
    protected ArrayOfInt notCancelledBids;

    /**
     * Gets the value of the cancelBidValue property.
     * 
     */
    public int getCancelBidValue() {
        return cancelBidValue;
    }

    /**
     * Sets the value of the cancelBidValue property.
     * 
     */
    public void setCancelBidValue(int value) {
        this.cancelBidValue = value;
    }

    /**
     * Gets the value of the cancelledBids property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getCancelledBids() {
        return cancelledBids;
    }

    /**
     * Sets the value of the cancelledBids property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setCancelledBids(ArrayOfInt value) {
        this.cancelledBids = value;
    }

    /**
     * Gets the value of the notCancelledBids property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getNotCancelledBids() {
        return notCancelledBids;
    }

    /**
     * Sets the value of the notCancelledBids property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setNotCancelledBids(ArrayOfInt value) {
        this.notCancelledBids = value;
    }

}
