//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="createdItemTemplate" type="{https://webapi.allegro.pl/service.php}CreatedItemTemplateStruct"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createdItemTemplate"
})
@XmlRootElement(name = "doCreateItemTemplateResponse")
public class DoCreateItemTemplateResponse {

    @XmlElement(required = true)
    protected CreatedItemTemplateStruct createdItemTemplate;

    /**
     * Gets the value of the createdItemTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link CreatedItemTemplateStruct }
     *     
     */
    public CreatedItemTemplateStruct getCreatedItemTemplate() {
        return createdItemTemplate;
    }

    /**
     * Sets the value of the createdItemTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatedItemTemplateStruct }
     *     
     */
    public void setCreatedItemTemplate(CreatedItemTemplateStruct value) {
        this.createdItemTemplate = value;
    }

}
