//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shopsTagsCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="shopsTags" type="{https://webapi.allegro.pl/service.php}ArrayOfShopstagtypestruct" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shopsTagsCount",
    "shopsTags"
})
@XmlRootElement(name = "doGetShopsTagsResponse")
public class DoGetShopsTagsResponse {

    protected int shopsTagsCount;
    protected ArrayOfShopstagtypestruct shopsTags;

    /**
     * Gets the value of the shopsTagsCount property.
     * 
     */
    public int getShopsTagsCount() {
        return shopsTagsCount;
    }

    /**
     * Sets the value of the shopsTagsCount property.
     * 
     */
    public void setShopsTagsCount(int value) {
        this.shopsTagsCount = value;
    }

    /**
     * Gets the value of the shopsTags property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfShopstagtypestruct }
     *     
     */
    public ArrayOfShopstagtypestruct getShopsTags() {
        return shopsTags;
    }

    /**
     * Sets the value of the shopsTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfShopstagtypestruct }
     *     
     */
    public void setShopsTags(ArrayOfShopstagtypestruct value) {
        this.shopsTags = value;
    }

}
