//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="itemListInfoExt" type="{https://webapi.allegro.pl/service.php}ItemInfoExt"/&gt;
 *         &lt;element name="itemCatPath" type="{https://webapi.allegro.pl/service.php}ArrayOfItemcatlist" minOccurs="0"/&gt;
 *         &lt;element name="itemImgList" type="{https://webapi.allegro.pl/service.php}ArrayOfItemimagelist" minOccurs="0"/&gt;
 *         &lt;element name="itemAttribList" type="{https://webapi.allegro.pl/service.php}ArrayOfAttribstruct" minOccurs="0"/&gt;
 *         &lt;element name="itemPostageOptions" type="{https://webapi.allegro.pl/service.php}ArrayOfPostagestruct" minOccurs="0"/&gt;
 *         &lt;element name="itemPaymentOptions" type="{https://webapi.allegro.pl/service.php}ItemPaymentOptions"/&gt;
 *         &lt;element name="itemCompanyInfo" type="{https://webapi.allegro.pl/service.php}CompanyInfoStruct"/&gt;
 *         &lt;element name="itemProductInfo" type="{https://webapi.allegro.pl/service.php}ProductStruct"/&gt;
 *         &lt;element name="itemVariants" type="{https://webapi.allegro.pl/service.php}ArrayOfItemvariantstruct" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemListInfoExt",
    "itemCatPath",
    "itemImgList",
    "itemAttribList",
    "itemPostageOptions",
    "itemPaymentOptions",
    "itemCompanyInfo",
    "itemProductInfo",
    "itemVariants"
})
@XmlRootElement(name = "doShowItemInfoExtResponse")
public class DoShowItemInfoExtResponse {

    @XmlElement(required = true)
    protected ItemInfoExt itemListInfoExt;
    protected ArrayOfItemcatlist itemCatPath;
    protected ArrayOfItemimagelist itemImgList;
    protected ArrayOfAttribstruct itemAttribList;
    protected ArrayOfPostagestruct itemPostageOptions;
    @XmlElement(required = true)
    protected ItemPaymentOptions itemPaymentOptions;
    @XmlElement(required = true)
    protected CompanyInfoStruct itemCompanyInfo;
    @XmlElement(required = true)
    protected ProductStruct itemProductInfo;
    protected ArrayOfItemvariantstruct itemVariants;

    /**
     * Gets the value of the itemListInfoExt property.
     * 
     * @return
     *     possible object is
     *     {@link ItemInfoExt }
     *     
     */
    public ItemInfoExt getItemListInfoExt() {
        return itemListInfoExt;
    }

    /**
     * Sets the value of the itemListInfoExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemInfoExt }
     *     
     */
    public void setItemListInfoExt(ItemInfoExt value) {
        this.itemListInfoExt = value;
    }

    /**
     * Gets the value of the itemCatPath property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemcatlist }
     *     
     */
    public ArrayOfItemcatlist getItemCatPath() {
        return itemCatPath;
    }

    /**
     * Sets the value of the itemCatPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemcatlist }
     *     
     */
    public void setItemCatPath(ArrayOfItemcatlist value) {
        this.itemCatPath = value;
    }

    /**
     * Gets the value of the itemImgList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemimagelist }
     *     
     */
    public ArrayOfItemimagelist getItemImgList() {
        return itemImgList;
    }

    /**
     * Sets the value of the itemImgList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemimagelist }
     *     
     */
    public void setItemImgList(ArrayOfItemimagelist value) {
        this.itemImgList = value;
    }

    /**
     * Gets the value of the itemAttribList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAttribstruct }
     *     
     */
    public ArrayOfAttribstruct getItemAttribList() {
        return itemAttribList;
    }

    /**
     * Sets the value of the itemAttribList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAttribstruct }
     *     
     */
    public void setItemAttribList(ArrayOfAttribstruct value) {
        this.itemAttribList = value;
    }

    /**
     * Gets the value of the itemPostageOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPostagestruct }
     *     
     */
    public ArrayOfPostagestruct getItemPostageOptions() {
        return itemPostageOptions;
    }

    /**
     * Sets the value of the itemPostageOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPostagestruct }
     *     
     */
    public void setItemPostageOptions(ArrayOfPostagestruct value) {
        this.itemPostageOptions = value;
    }

    /**
     * Gets the value of the itemPaymentOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPaymentOptions }
     *     
     */
    public ItemPaymentOptions getItemPaymentOptions() {
        return itemPaymentOptions;
    }

    /**
     * Sets the value of the itemPaymentOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPaymentOptions }
     *     
     */
    public void setItemPaymentOptions(ItemPaymentOptions value) {
        this.itemPaymentOptions = value;
    }

    /**
     * Gets the value of the itemCompanyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyInfoStruct }
     *     
     */
    public CompanyInfoStruct getItemCompanyInfo() {
        return itemCompanyInfo;
    }

    /**
     * Sets the value of the itemCompanyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyInfoStruct }
     *     
     */
    public void setItemCompanyInfo(CompanyInfoStruct value) {
        this.itemCompanyInfo = value;
    }

    /**
     * Gets the value of the itemProductInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductStruct }
     *     
     */
    public ProductStruct getItemProductInfo() {
        return itemProductInfo;
    }

    /**
     * Sets the value of the itemProductInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductStruct }
     *     
     */
    public void setItemProductInfo(ProductStruct value) {
        this.itemProductInfo = value;
    }

    /**
     * Gets the value of the itemVariants property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemvariantstruct }
     *     
     */
    public ArrayOfItemvariantstruct getItemVariants() {
        return itemVariants;
    }

    /**
     * Sets the value of the itemVariants property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemvariantstruct }
     *     
     */
    public void setItemVariants(ArrayOfItemvariantstruct value) {
        this.itemVariants = value;
    }

}
