//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewPostBuyFormCommonStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewPostBuyFormCommonStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="paymentMethodId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shipmentAddressType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="shipmentAddressData" type="{https://webapi.allegro.pl/service.php}AddressUserDataStruct" minOccurs="0"/&gt;
 *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="invoiceOption" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="invoiceInfo" type="{https://webapi.allegro.pl/service.php}InvoiceInfoStruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewPostBuyFormCommonStruct", propOrder = {

})
public class NewPostBuyFormCommonStruct {

    @XmlElement(required = true)
    protected String paymentMethodId;
    protected int shipmentAddressType;
    protected AddressUserDataStruct shipmentAddressData;
    protected String contactPhone;
    protected int invoiceOption;
    protected InvoiceInfoStruct invoiceInfo;

    /**
     * Gets the value of the paymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * Sets the value of the paymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethodId(String value) {
        this.paymentMethodId = value;
    }

    /**
     * Gets the value of the shipmentAddressType property.
     * 
     */
    public int getShipmentAddressType() {
        return shipmentAddressType;
    }

    /**
     * Sets the value of the shipmentAddressType property.
     * 
     */
    public void setShipmentAddressType(int value) {
        this.shipmentAddressType = value;
    }

    /**
     * Gets the value of the shipmentAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link AddressUserDataStruct }
     *     
     */
    public AddressUserDataStruct getShipmentAddressData() {
        return shipmentAddressData;
    }

    /**
     * Sets the value of the shipmentAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressUserDataStruct }
     *     
     */
    public void setShipmentAddressData(AddressUserDataStruct value) {
        this.shipmentAddressData = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the invoiceOption property.
     * 
     */
    public int getInvoiceOption() {
        return invoiceOption;
    }

    /**
     * Sets the value of the invoiceOption property.
     * 
     */
    public void setInvoiceOption(int value) {
        this.invoiceOption = value;
    }

    /**
     * Gets the value of the invoiceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceInfoStruct }
     *     
     */
    public InvoiceInfoStruct getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * Sets the value of the invoiceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceInfoStruct }
     *     
     */
    public void setInvoiceInfo(InvoiceInfoStruct value) {
        this.invoiceInfo = value;
    }

}
