//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParameterInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="parameterName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="parameterValue" type="{https://webapi.allegro.pl/service.php}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="parameterUnit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="parameterIsRange" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterInfoType", propOrder = {

})
public class ParameterInfoType {

    @XmlElement(required = true)
    protected String parameterName;
    protected ArrayOfString parameterValue;
    @XmlElement(required = true)
    protected String parameterUnit;
    protected boolean parameterIsRange;

    /**
     * Gets the value of the parameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the parameterValue property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getParameterValue() {
        return parameterValue;
    }

    /**
     * Sets the value of the parameterValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setParameterValue(ArrayOfString value) {
        this.parameterValue = value;
    }

    /**
     * Gets the value of the parameterUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterUnit() {
        return parameterUnit;
    }

    /**
     * Sets the value of the parameterUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterUnit(String value) {
        this.parameterUnit = value;
    }

    /**
     * Gets the value of the parameterIsRange property.
     * 
     */
    public boolean isParameterIsRange() {
        return parameterIsRange;
    }

    /**
     * Sets the value of the parameterIsRange property.
     * 
     */
    public void setParameterIsRange(boolean value) {
        this.parameterIsRange = value;
    }

}
