//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentSellersStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentSellersStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="payTransSellerId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="payTransSellerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payTransItems" type="{https://webapi.allegro.pl/service.php}ArrayOfPaymentitemsstruct" minOccurs="0"/&gt;
 *         &lt;element name="payTransSellerPostageAmount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentSellersStruct", propOrder = {

})
public class PaymentSellersStruct {

    protected int payTransSellerId;
    @XmlElement(required = true)
    protected String payTransSellerName;
    protected ArrayOfPaymentitemsstruct payTransItems;
    protected float payTransSellerPostageAmount;

    /**
     * Gets the value of the payTransSellerId property.
     * 
     */
    public int getPayTransSellerId() {
        return payTransSellerId;
    }

    /**
     * Sets the value of the payTransSellerId property.
     * 
     */
    public void setPayTransSellerId(int value) {
        this.payTransSellerId = value;
    }

    /**
     * Gets the value of the payTransSellerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayTransSellerName() {
        return payTransSellerName;
    }

    /**
     * Sets the value of the payTransSellerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayTransSellerName(String value) {
        this.payTransSellerName = value;
    }

    /**
     * Gets the value of the payTransItems property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPaymentitemsstruct }
     *     
     */
    public ArrayOfPaymentitemsstruct getPayTransItems() {
        return payTransItems;
    }

    /**
     * Sets the value of the payTransItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPaymentitemsstruct }
     *     
     */
    public void setPayTransItems(ArrayOfPaymentitemsstruct value) {
        this.payTransItems = value;
    }

    /**
     * Gets the value of the payTransSellerPostageAmount property.
     * 
     */
    public float getPayTransSellerPostageAmount() {
        return payTransSellerPostageAmount;
    }

    /**
     * Sets the value of the payTransSellerPostageAmount property.
     * 
     */
    public void setPayTransSellerPostageAmount(float value) {
        this.payTransSellerPostageAmount = value;
    }

}
