//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostBuyFormShipmentTrackingStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostBuyFormShipmentTrackingStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="postBuyFormOperatorId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="postBuyFormPackageId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="postBuyFormPackageStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostBuyFormShipmentTrackingStruct", propOrder = {

})
public class PostBuyFormShipmentTrackingStruct {

    protected int postBuyFormOperatorId;
    @XmlElement(required = true)
    protected String postBuyFormPackageId;
    @XmlElement(required = true)
    protected String postBuyFormPackageStatus;

    /**
     * Gets the value of the postBuyFormOperatorId property.
     * 
     */
    public int getPostBuyFormOperatorId() {
        return postBuyFormOperatorId;
    }

    /**
     * Sets the value of the postBuyFormOperatorId property.
     * 
     */
    public void setPostBuyFormOperatorId(int value) {
        this.postBuyFormOperatorId = value;
    }

    /**
     * Gets the value of the postBuyFormPackageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostBuyFormPackageId() {
        return postBuyFormPackageId;
    }

    /**
     * Sets the value of the postBuyFormPackageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostBuyFormPackageId(String value) {
        this.postBuyFormPackageId = value;
    }

    /**
     * Gets the value of the postBuyFormPackageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostBuyFormPackageStatus() {
        return postBuyFormPackageStatus;
    }

    /**
     * Sets the value of the postBuyFormPackageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostBuyFormPackageStatus(String value) {
        this.postBuyFormPackageStatus = value;
    }

}
