//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostBuyFormStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostBuyFormStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="transactionPackageIds" type="{https://webapi.allegro.pl/service.php}ArrayOfLong" minOccurs="0"/&gt;
 *         &lt;element name="transactionPayByLink" type="{https://webapi.allegro.pl/service.php}TransactionPayByLinkStruct"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostBuyFormStruct", propOrder = {

})
public class PostBuyFormStruct {

    protected long transactionId;
    protected ArrayOfLong transactionPackageIds;
    @XmlElement(required = true)
    protected TransactionPayByLinkStruct transactionPayByLink;

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the transactionPackageIds property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLong }
     *     
     */
    public ArrayOfLong getTransactionPackageIds() {
        return transactionPackageIds;
    }

    /**
     * Sets the value of the transactionPackageIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLong }
     *     
     */
    public void setTransactionPackageIds(ArrayOfLong value) {
        this.transactionPackageIds = value;
    }

    /**
     * Gets the value of the transactionPayByLink property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionPayByLinkStruct }
     *     
     */
    public TransactionPayByLinkStruct getTransactionPayByLink() {
        return transactionPayByLink;
    }

    /**
     * Sets the value of the transactionPayByLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionPayByLinkStruct }
     *     
     */
    public void setTransactionPayByLink(TransactionPayByLinkStruct value) {
        this.transactionPayByLink = value;
    }

}
