//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedItemsShipmentDataStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedItemsShipmentDataStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sellerShipmentData" type="{https://webapi.allegro.pl/service.php}ArrayOfSellershipmentdatastruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedItemsShipmentDataStruct", propOrder = {

})
public class RelatedItemsShipmentDataStruct {

    protected ArrayOfSellershipmentdatastruct sellerShipmentData;

    /**
     * Gets the value of the sellerShipmentData property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSellershipmentdatastruct }
     *     
     */
    public ArrayOfSellershipmentdatastruct getSellerShipmentData() {
        return sellerShipmentData;
    }

    /**
     * Sets the value of the sellerShipmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSellershipmentdatastruct }
     *     
     */
    public void setSellerShipmentData(ArrayOfSellershipmentdatastruct value) {
        this.sellerShipmentData = value;
    }

}
