//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedItemsStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedItemsStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="relatedItemsInfo" type="{https://webapi.allegro.pl/service.php}ArrayOfRelateditemstruct" minOccurs="0"/&gt;
 *         &lt;element name="relatedItemsAmount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedItemsStruct", propOrder = {

})
public class RelatedItemsStruct {

    protected ArrayOfRelateditemstruct relatedItemsInfo;
    protected float relatedItemsAmount;

    /**
     * Gets the value of the relatedItemsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRelateditemstruct }
     *     
     */
    public ArrayOfRelateditemstruct getRelatedItemsInfo() {
        return relatedItemsInfo;
    }

    /**
     * Sets the value of the relatedItemsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRelateditemstruct }
     *     
     */
    public void setRelatedItemsInfo(ArrayOfRelateditemstruct value) {
        this.relatedItemsInfo = value;
    }

    /**
     * Gets the value of the relatedItemsAmount property.
     * 
     */
    public float getRelatedItemsAmount() {
        return relatedItemsAmount;
    }

    /**
     * Sets the value of the relatedItemsAmount property.
     * 
     */
    public void setRelatedItemsAmount(float value) {
        this.relatedItemsAmount = value;
    }

}
