//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellRatingAveragePerMonthStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellRatingAveragePerMonthStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sellRatingMonth" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sellRatingAverageValues" type="{https://webapi.allegro.pl/service.php}ArrayOfSellratingstatsstruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellRatingAveragePerMonthStruct", propOrder = {

})
public class SellRatingAveragePerMonthStruct {

    @XmlElement(required = true)
    protected String sellRatingMonth;
    protected ArrayOfSellratingstatsstruct sellRatingAverageValues;

    /**
     * Gets the value of the sellRatingMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellRatingMonth() {
        return sellRatingMonth;
    }

    /**
     * Sets the value of the sellRatingMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellRatingMonth(String value) {
        this.sellRatingMonth = value;
    }

    /**
     * Gets the value of the sellRatingAverageValues property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSellratingstatsstruct }
     *     
     */
    public ArrayOfSellratingstatsstruct getSellRatingAverageValues() {
        return sellRatingAverageValues;
    }

    /**
     * Sets the value of the sellRatingAverageValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSellratingstatsstruct }
     *     
     */
    public void setSellRatingAverageValues(ArrayOfSellratingstatsstruct value) {
        this.sellRatingAverageValues = value;
    }

}
