//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellRatingReasonSumStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellRatingReasonSumStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sellRatingReasonTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sellRatingReasonCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellRatingReasonSumStruct", propOrder = {

})
public class SellRatingReasonSumStruct {

    @XmlElement(required = true)
    protected String sellRatingReasonTitle;
    protected int sellRatingReasonCount;

    /**
     * Gets the value of the sellRatingReasonTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellRatingReasonTitle() {
        return sellRatingReasonTitle;
    }

    /**
     * Sets the value of the sellRatingReasonTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellRatingReasonTitle(String value) {
        this.sellRatingReasonTitle = value;
    }

    /**
     * Gets the value of the sellRatingReasonCount property.
     * 
     */
    public int getSellRatingReasonCount() {
        return sellRatingReasonCount;
    }

    /**
     * Sets the value of the sellRatingReasonCount property.
     * 
     */
    public void setSellRatingReasonCount(int value) {
        this.sellRatingReasonCount = value;
    }

}
