//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellRatingInfoStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellRatingInfoStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sellRatingGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sellRatingGroupTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sellRatingReasons" type="{https://webapi.allegro.pl/service.php}ArrayOfSellratingreasonstruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellRatingInfoStruct", propOrder = {

})
public class SellRatingInfoStruct {

    protected int sellRatingGroupId;
    @XmlElement(required = true)
    protected String sellRatingGroupTitle;
    protected ArrayOfSellratingreasonstruct sellRatingReasons;

    /**
     * Gets the value of the sellRatingGroupId property.
     * 
     */
    public int getSellRatingGroupId() {
        return sellRatingGroupId;
    }

    /**
     * Sets the value of the sellRatingGroupId property.
     * 
     */
    public void setSellRatingGroupId(int value) {
        this.sellRatingGroupId = value;
    }

    /**
     * Gets the value of the sellRatingGroupTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellRatingGroupTitle() {
        return sellRatingGroupTitle;
    }

    /**
     * Sets the value of the sellRatingGroupTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellRatingGroupTitle(String value) {
        this.sellRatingGroupTitle = value;
    }

    /**
     * Gets the value of the sellRatingReasons property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSellratingreasonstruct }
     *     
     */
    public ArrayOfSellratingreasonstruct getSellRatingReasons() {
        return sellRatingReasons;
    }

    /**
     * Sets the value of the sellRatingReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSellratingreasonstruct }
     *     
     */
    public void setSellRatingReasons(ArrayOfSellratingreasonstruct value) {
        this.sellRatingReasons = value;
    }

}
