//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellerPaymentInfoStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellerPaymentInfoStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="shipmentPaymentInfoPza" type="{https://webapi.allegro.pl/service.php}ArrayOfShipmentpaymentinfostruct" minOccurs="0"/&gt;
 *         &lt;element name="shipmentPaymentInfoNonPza" type="{https://webapi.allegro.pl/service.php}ArrayOfShipmentpaymentinfostruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellerPaymentInfoStruct", propOrder = {

})
public class SellerPaymentInfoStruct {

    protected ArrayOfShipmentpaymentinfostruct shipmentPaymentInfoPza;
    protected ArrayOfShipmentpaymentinfostruct shipmentPaymentInfoNonPza;

    /**
     * Gets the value of the shipmentPaymentInfoPza property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfShipmentpaymentinfostruct }
     *     
     */
    public ArrayOfShipmentpaymentinfostruct getShipmentPaymentInfoPza() {
        return shipmentPaymentInfoPza;
    }

    /**
     * Sets the value of the shipmentPaymentInfoPza property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfShipmentpaymentinfostruct }
     *     
     */
    public void setShipmentPaymentInfoPza(ArrayOfShipmentpaymentinfostruct value) {
        this.shipmentPaymentInfoPza = value;
    }

    /**
     * Gets the value of the shipmentPaymentInfoNonPza property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfShipmentpaymentinfostruct }
     *     
     */
    public ArrayOfShipmentpaymentinfostruct getShipmentPaymentInfoNonPza() {
        return shipmentPaymentInfoNonPza;
    }

    /**
     * Sets the value of the shipmentPaymentInfoNonPza property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfShipmentpaymentinfostruct }
     *     
     */
    public void setShipmentPaymentInfoNonPza(ArrayOfShipmentpaymentinfostruct value) {
        this.shipmentPaymentInfoNonPza = value;
    }

}
