//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellRatingEstimationStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellRatingEstimationStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sellRatingGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sellRatingGroupEstimation" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sellRatingReasonId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellRatingEstimationStruct", propOrder = {

})
public class SellRatingEstimationStruct {

    protected int sellRatingGroupId;
    protected int sellRatingGroupEstimation;
    protected Integer sellRatingReasonId;

    /**
     * Gets the value of the sellRatingGroupId property.
     * 
     */
    public int getSellRatingGroupId() {
        return sellRatingGroupId;
    }

    /**
     * Sets the value of the sellRatingGroupId property.
     * 
     */
    public void setSellRatingGroupId(int value) {
        this.sellRatingGroupId = value;
    }

    /**
     * Gets the value of the sellRatingGroupEstimation property.
     * 
     */
    public int getSellRatingGroupEstimation() {
        return sellRatingGroupEstimation;
    }

    /**
     * Sets the value of the sellRatingGroupEstimation property.
     * 
     */
    public void setSellRatingGroupEstimation(int value) {
        this.sellRatingGroupEstimation = value;
    }

    /**
     * Gets the value of the sellRatingReasonId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSellRatingReasonId() {
        return sellRatingReasonId;
    }

    /**
     * Sets the value of the sellRatingReasonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSellRatingReasonId(Integer value) {
        this.sellRatingReasonId = value;
    }

}
