//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentPaymentInfoStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentPaymentInfoStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="shipmentId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="shipmentName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shipmentAmount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="shipmentPaymentType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="shipmentItemIds" type="{https://webapi.allegro.pl/service.php}ArrayOfLong" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentPaymentInfoStruct", propOrder = {

})
public class ShipmentPaymentInfoStruct {

    protected int shipmentId;
    @XmlElement(required = true)
    protected String shipmentName;
    protected float shipmentAmount;
    protected int shipmentPaymentType;
    protected ArrayOfLong shipmentItemIds;

    /**
     * Gets the value of the shipmentId property.
     * 
     */
    public int getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     */
    public void setShipmentId(int value) {
        this.shipmentId = value;
    }

    /**
     * Gets the value of the shipmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentName() {
        return shipmentName;
    }

    /**
     * Sets the value of the shipmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentName(String value) {
        this.shipmentName = value;
    }

    /**
     * Gets the value of the shipmentAmount property.
     * 
     */
    public float getShipmentAmount() {
        return shipmentAmount;
    }

    /**
     * Sets the value of the shipmentAmount property.
     * 
     */
    public void setShipmentAmount(float value) {
        this.shipmentAmount = value;
    }

    /**
     * Gets the value of the shipmentPaymentType property.
     * 
     */
    public int getShipmentPaymentType() {
        return shipmentPaymentType;
    }

    /**
     * Sets the value of the shipmentPaymentType property.
     * 
     */
    public void setShipmentPaymentType(int value) {
        this.shipmentPaymentType = value;
    }

    /**
     * Gets the value of the shipmentItemIds property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLong }
     *     
     */
    public ArrayOfLong getShipmentItemIds() {
        return shipmentItemIds;
    }

    /**
     * Sets the value of the shipmentItemIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLong }
     *     
     */
    public void setShipmentItemIds(ArrayOfLong value) {
        this.shipmentItemIds = value;
    }

}
