//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionPayByLinkStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionPayByLinkStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="actionHttpMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="actionUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="actionData" type="{https://webapi.allegro.pl/service.php}ArrayOfActiondatastruct" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionPayByLinkStruct", propOrder = {

})
public class TransactionPayByLinkStruct {

    @XmlElement(required = true)
    protected String actionHttpMethod;
    @XmlElement(required = true)
    protected String actionUrl;
    protected ArrayOfActiondatastruct actionData;

    /**
     * Gets the value of the actionHttpMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionHttpMethod() {
        return actionHttpMethod;
    }

    /**
     * Sets the value of the actionHttpMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionHttpMethod(String value) {
        this.actionHttpMethod = value;
    }

    /**
     * Gets the value of the actionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * Sets the value of the actionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionUrl(String value) {
        this.actionUrl = value;
    }

    /**
     * Gets the value of the actionData property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfActiondatastruct }
     *     
     */
    public ArrayOfActiondatastruct getActionData() {
        return actionData;
    }

    /**
     * Sets the value of the actionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfActiondatastruct }
     *     
     */
    public void setActionData(ArrayOfActiondatastruct value) {
        this.actionData = value;
    }

}
