//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserPaymentRefundsStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserPaymentRefundsStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="payRefundTransId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="payRefundItId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="payRefundSellerId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="payRefundValue" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="payRefundReason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payRefundDate" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserPaymentRefundsStruct", propOrder = {

})
public class UserPaymentRefundsStruct {

    protected long payRefundTransId;
    protected long payRefundItId;
    protected int payRefundSellerId;
    protected float payRefundValue;
    @XmlElement(required = true)
    protected String payRefundReason;
    protected long payRefundDate;

    /**
     * Gets the value of the payRefundTransId property.
     * 
     */
    public long getPayRefundTransId() {
        return payRefundTransId;
    }

    /**
     * Sets the value of the payRefundTransId property.
     * 
     */
    public void setPayRefundTransId(long value) {
        this.payRefundTransId = value;
    }

    /**
     * Gets the value of the payRefundItId property.
     * 
     */
    public long getPayRefundItId() {
        return payRefundItId;
    }

    /**
     * Sets the value of the payRefundItId property.
     * 
     */
    public void setPayRefundItId(long value) {
        this.payRefundItId = value;
    }

    /**
     * Gets the value of the payRefundSellerId property.
     * 
     */
    public int getPayRefundSellerId() {
        return payRefundSellerId;
    }

    /**
     * Sets the value of the payRefundSellerId property.
     * 
     */
    public void setPayRefundSellerId(int value) {
        this.payRefundSellerId = value;
    }

    /**
     * Gets the value of the payRefundValue property.
     * 
     */
    public float getPayRefundValue() {
        return payRefundValue;
    }

    /**
     * Sets the value of the payRefundValue property.
     * 
     */
    public void setPayRefundValue(float value) {
        this.payRefundValue = value;
    }

    /**
     * Gets the value of the payRefundReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayRefundReason() {
        return payRefundReason;
    }

    /**
     * Sets the value of the payRefundReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayRefundReason(String value) {
        this.payRefundReason = value;
    }

    /**
     * Gets the value of the payRefundDate property.
     * 
     */
    public long getPayRefundDate() {
        return payRefundDate;
    }

    /**
     * Sets the value of the payRefundDate property.
     * 
     */
    public void setPayRefundDate(long value) {
        this.payRefundDate = value;
    }

}
