//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:50:52 PM CET 
//


package pl.quider.web.allegro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaitFeedbackStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaitFeedbackStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="feItemId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="feItemName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="feToUserId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="feOp" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="feAnsCommentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fePossibilityToAdd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaitFeedbackStruct", propOrder = {

})
public class WaitFeedbackStruct {

    protected long feItemId;
    @XmlElement(required = true)
    protected String feItemName;
    protected int feToUserId;
    protected int feOp;
    @XmlElement(required = true)
    protected String feAnsCommentType;
    protected int fePossibilityToAdd;

    /**
     * Gets the value of the feItemId property.
     * 
     */
    public long getFeItemId() {
        return feItemId;
    }

    /**
     * Sets the value of the feItemId property.
     * 
     */
    public void setFeItemId(long value) {
        this.feItemId = value;
    }

    /**
     * Gets the value of the feItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeItemName() {
        return feItemName;
    }

    /**
     * Sets the value of the feItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeItemName(String value) {
        this.feItemName = value;
    }

    /**
     * Gets the value of the feToUserId property.
     * 
     */
    public int getFeToUserId() {
        return feToUserId;
    }

    /**
     * Sets the value of the feToUserId property.
     * 
     */
    public void setFeToUserId(int value) {
        this.feToUserId = value;
    }

    /**
     * Gets the value of the feOp property.
     * 
     */
    public int getFeOp() {
        return feOp;
    }

    /**
     * Sets the value of the feOp property.
     * 
     */
    public void setFeOp(int value) {
        this.feOp = value;
    }

    /**
     * Gets the value of the feAnsCommentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeAnsCommentType() {
        return feAnsCommentType;
    }

    /**
     * Sets the value of the feAnsCommentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeAnsCommentType(String value) {
        this.feAnsCommentType = value;
    }

    /**
     * Gets the value of the fePossibilityToAdd property.
     * 
     */
    public int getFePossibilityToAdd() {
        return fePossibilityToAdd;
    }

    /**
     * Sets the value of the fePossibilityToAdd property.
     * 
     */
    public void setFePossibilityToAdd(int value) {
        this.fePossibilityToAdd = value;
    }

}
